### ISSUE TITLE
Casa compartilhada com problema

### ISSUE THREAD

**Issue by hartturmch** [kitoide/everest-rp-vrp-fivem#1]
você pode adicionar quantas pessoas quiser na casa compartilhada, desde que não saia e entre da casa quando adiciona a pessoa. fica lá parado adicionando todo mundo do servidor se quiser.
Para o menu sumir você tem que sair e entrar na casa, caso você não faça isso o menu "adicionar morador" fica infinito lá.

**Comment by thiagosmagalhaes** [comment]
Ajustes somente na versão paga
